import {
  ArrowRight,
  Boxes,
  FileUp,
  Binary,
  Database,
  Sparkles,
  Quote,
  Cpu,
  SlidersHorizontal,
  FileText,
  MessageSquare,
  Layers3,
  ShieldCheck,
  Info,
} from 'lucide-react'
import { GithubIcon } from '../components/ui/icons'
import MarketingNav from '../components/marketing/MarketingNav'
import MarketingFooter from '../components/marketing/MarketingFooter'
import PipelineFlow from '../components/marketing/PipelineFlow'
import Badge from '../components/ui/Badge'
import { LinkButton } from '../components/ui/Button'
import StatusPill from '../components/ui/StatusPill'
import { formatNumber } from '../lib/format'

const GITHUB_URL = 'https://github.com/your-org/rag-starter'

const FEATURES = [
  {
    icon: Boxes,
    title: 'Modular RAG Pipeline',
    body: 'Swap extraction, chunking, embedding or the LLM independently. Every stage is a clean seam, not a tangle.',
  },
  {
    icon: FileUp,
    title: 'PDF Ingestion',
    body: 'Drag a PDF into the UI or use the CLI. Text is extracted, cleaned and chunked with sensible defaults.',
  },
  {
    icon: Binary,
    title: 'Embedding & Vector Search',
    body: 'Configurable embedding models — English or multilingual — with cosine similarity retrieval out of the box.',
  },
  {
    icon: Database,
    title: 'Qdrant Integration',
    body: 'Runs Qdrant as a real server via Docker Compose. No locked on-disk store, no 501s on ingest.',
  },
  {
    icon: Sparkles,
    title: 'Gemini Integration',
    body: 'Answers are generated by Gemini with retrieved context injected — model and parameters set from .env.',
  },
  {
    icon: Quote,
    title: 'Source-Aware Answers',
    body: 'Every answer ships with the document and page it came from, plus a relevance score for each chunk.',
  },
  {
    icon: Layers3,
    title: 'React + .NET + Python',
    body: 'A typed React client, an ASP.NET Core API gateway and a focused Python RAG service — cleanly separated.',
  },
  {
    icon: SlidersHorizontal,
    title: 'Easy Configuration',
    body: 'Chunk size, overlap, top-K, collection name and providers all live in one documented .env file.',
  },
]

const TECHS = [
  { name: 'React', icon: Layers3 },
  { name: 'ASP.NET Core', icon: ShieldCheck },
  { name: 'Python', icon: Cpu },
  { name: 'Qdrant', icon: Database },
  { name: 'Gemini', icon: Sparkles },
]

const ARCH_TIERS = [
  {
    badge: 'Client',
    name: 'React',
    body: 'Single-page app. Talks only to the .NET API over HTTP/JSON.',
  },
  {
    badge: 'Gateway',
    name: 'ASP.NET Core',
    body: 'Validates uploads, enforces limits, forwards ingestion and chat to the RAG service.',
  },
  {
    badge: 'Engine',
    name: 'Python RAG',
    body: 'Extract → clean → chunk → embed, and retrieve → assemble context → call Gemini.',
  },
  {
    badge: 'Storage & LLM',
    name: 'Qdrant + Gemini',
    body: 'Qdrant server holds the vectors; Gemini generates the grounded answer.',
  },
]

const DX_STEPS = [
  { n: 1, title: 'Clone', body: 'git clone the repository and open it.' },
  { n: 2, title: 'Configure', body: 'Copy .env.example, set your Gemini key and models.' },
  { n: 3, title: 'Add PDF', body: 'Drop a PDF in the Documents page — or run the CLI.' },
  { n: 4, title: 'Run', body: 'docker compose up brings the whole stack online.' },
  { n: 5, title: 'Ask', body: 'Open Knowledge Chat and ask questions with sources.' },
]

export default function LandingPage() {
  return (
    <div className="marketing">
      <MarketingNav />

      {/* Hero */}
      <section className="hero">
        <div className="container hero__inner">
          <div>
            <Badge tone="primary" dot>
              Open-source RAG Starter
            </Badge>
            <h1 className="hero__title">
              Build RAG Systems.{' '}
              <span className="grad">Without Starting From Zero.</span>
            </h1>
            <p className="hero__sub">
              A modular, developer-friendly RAG starter that lets you clone,
              configure, ingest your documents, and start asking questions —
              with sources attached to every answer.
            </p>
            <div className="hero__ctas">
              <LinkButton size="lg" to="/signup">
                Get Started
                <ArrowRight size={16} />
              </LinkButton>
              <LinkButton variant="secondary" size="lg" href={GITHUB_URL}>
                <GithubIcon size={16} />
                View on GitHub
              </LinkButton>
            </div>
            <div className="hero__phrase">
              <span>Clone</span>
              <span>Configure</span>
              <span>Ingest</span>
              <span>Ask</span>
            </div>
          </div>

          <div className="stack" style={{ gap: 'var(--sp-4)' }}>
            <PipelineFlow
              title="Ingestion"
              nodes={[
                { label: 'PDF', icon: FileText },
                { label: 'Extract', icon: FileUp },
                { label: 'Clean' },
                { label: 'Chunk' },
                { label: 'Embed', icon: Binary },
                { label: 'Qdrant', icon: Database, primary: true },
              ]}
            />
            <PipelineFlow
              title="Query"
              nodes={[
                { label: 'Question', icon: MessageSquare },
                { label: 'Embed', icon: Binary },
                { label: 'Retrieve', icon: Database },
                { label: 'Context' },
                { label: 'Gemini', icon: Sparkles, primary: true },
                { label: 'Answer + Sources', icon: Quote },
              ]}
            />
          </div>
        </div>
      </section>

      {/* Trust */}
      <section className="section section--tight">
        <div className="container trust">
          <span className="trust__label">Built on a stack you already know</span>
          <div className="trust__row">
            {TECHS.map((t) => (
              <span className="tech" key={t.name}>
                <span className="tech__icon">
                  <t.icon size={16} />
                </span>
                {t.name}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="section" id="features">
        <div className="container">
          <div className="section-head section-head--center">
            <span className="eyebrow">Features</span>
            <h2>Everything a retrieval system needs, wired together</h2>
            <p>
              RAG Starter is not a demo notebook. It is the boring, correct
              plumbing you would otherwise rebuild on every project.
            </p>
          </div>
          <div className="features__grid">
            {FEATURES.map((f) => (
              <article className="card card--interactive feature" key={f.title}>
                <span className="feature__icon">
                  <f.icon />
                </span>
                <h3>{f.title}</h3>
                <p>{f.body}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="section" id="how">
        <div className="container">
          <div className="section-head section-head--center">
            <span className="eyebrow">How It Works</span>
            <h2>Two pipelines, one mental model</h2>
            <p>
              Documents go in once. Questions flow through the same vector space
              every time.
            </p>
          </div>
          <div className="how__lanes">
            <PipelineFlow
              title="1 · Ingestion pipeline"
              nodes={[
                { label: 'PDF', icon: FileText },
                { label: 'Extract text', icon: FileUp },
                { label: 'Clean' },
                { label: 'Chunk' },
                { label: 'Embed', icon: Binary },
                { label: 'Qdrant', icon: Database, primary: true },
              ]}
            />
            <PipelineFlow
              title="2 · Query pipeline"
              nodes={[
                { label: 'Question', icon: MessageSquare },
                { label: 'Embed', icon: Binary },
                { label: 'Retrieve', icon: Database },
                { label: 'Context' },
                { label: 'Gemini', icon: Sparkles, primary: true },
                { label: 'Answer + Sources', icon: Quote },
              ]}
            />
          </div>
        </div>
      </section>

      {/* Architecture */}
      <section className="section" id="architecture">
        <div className="container">
          <div className="section-head section-head--center">
            <span className="eyebrow">Architecture</span>
            <h2>React → ASP.NET Core → Python RAG → Qdrant + Gemini</h2>
            <p>
              A single request path, each layer with one job.
            </p>
          </div>
          <div className="arch">
            <div className="arch__row">
              {ARCH_TIERS.map((tier) => (
                <div className="arch__tier" key={tier.name}>
                  <span className="badge badge--accent">{tier.badge}</span>
                  <h3>{tier.name}</h3>
                  <p>{tier.body}</p>
                </div>
              ))}
            </div>
            <div className="arch__note">
              <Info />
              <span>
                The React frontend communicates <strong>only</strong> with the
                ASP.NET Core API. It never calls the Python RAG service directly —
                the .NET layer is the single gateway that validates, limits and
                forwards every request.
              </span>
            </div>
          </div>
        </div>
      </section>

      {/* Dashboard preview */}
      <section className="section">
        <div className="container">
          <div className="section-head section-head--center">
            <span className="eyebrow">Product Preview</span>
            <h2>A real workspace, not a chat box</h2>
            <p>
              Track documents, chunks, questions and sources — and see the health
              of every service at a glance.
            </p>
          </div>
          <div className="preview">
            <div className="preview__bar">
              <i />
              <i />
              <i />
              <span className="preview__url">app.ragstarter.dev/dashboard</span>
            </div>
            <div className="preview__body">
              <div className="preview__side">
                <span className="preview__navitem preview__navitem--active">
                  Dashboard
                </span>
                <span className="preview__navitem">Documents</span>
                <span className="preview__navitem">Knowledge Chat</span>
                <span className="preview__navitem">Settings</span>
                <span className="preview__navitem">Documentation</span>
              </div>
              <div className="preview__main">
                <div className="preview__stats">
                  {[
                    ['Documents', '5'],
                    ['Chunks', formatNumber(2020)],
                    ['Questions', '128'],
                    ['Sources cited', '392'],
                  ].map(([label, value]) => (
                    <div className="card" key={label} style={{ padding: 'var(--sp-4)' }}>
                      <div className="stat__value" style={{ fontSize: '1.3rem' }}>
                        {value}
                      </div>
                      <div className="stat__label">{label}</div>
                    </div>
                  ))}
                </div>
                <div className="preview__cols">
                  <div className="card" style={{ padding: 'var(--sp-4)' }}>
                    <div className="panel-head">
                      <h3>Recent documents</h3>
                    </div>
                    <div className="list">
                      {[
                        ['English-Grammar-In-Use.pdf', 'Ready'],
                        ['Platform-Architecture-Spec-v3.pdf', 'Ready'],
                        ['Employee-Onboarding-Handbook.pdf', 'Processing'],
                      ].map(([name, st]) => (
                        <div className="list__row" key={name}>
                          <span className="list__icon">
                            <FileText />
                          </span>
                          <span className="grow truncate">{name}</span>
                          <StatusPill
                            status={st === 'Ready' ? 'ready' : 'processing'}
                          />
                        </div>
                      ))}
                    </div>
                  </div>
                  <div className="card" style={{ padding: 'var(--sp-4)' }}>
                    <div className="panel-head">
                      <h3>System status</h3>
                    </div>
                    <div className="list">
                      {['API', 'RAG service', 'Qdrant', 'Gemini'].map((s) => (
                        <div className="health__row" key={s}>
                          <span>{s}</span>
                          <StatusPill status="ok" />
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Developer experience */}
      <section className="section">
        <div className="container">
          <div className="section-head">
            <span className="eyebrow">Developer Experience</span>
            <h2>Clone → Configure → Add PDF → Run → Ask</h2>
            <p>
              The whole point of RAG Starter: go from an empty folder to grounded
              answers in five commands.
            </p>
          </div>
          <div className="dx">
            <div className="dx__steps">
              {DX_STEPS.map((s) => (
                <div className="dx__step" key={s.n}>
                  <span className="dx__num">{s.n}</span>
                  <div>
                    <h3>{s.title}</h3>
                    <p>{s.body}</p>
                  </div>
                </div>
              ))}
            </div>
            <div className="terminal">
              <div className="terminal__bar">
                <i />
                <i />
                <i />
              </div>
              <div className="terminal__body">
                <div>
                  <span className="c-prompt">$ </span>
                  <span className="c-cmd">git clone https://github.com/your-org/rag-starter</span>
                </div>
                <div>
                  <span className="c-prompt">$ </span>
                  <span className="c-cmd">cp .env.example .env &amp;&amp; $EDITOR .env</span>
                </div>
                <div>
                  <span className="c-prompt">$ </span>
                  <span className="c-cmd">docker compose up -d</span>
                </div>
                <div className="c-ok"> ✔ frontend · api · rag · qdrant are up</div>
                <div>
                  <span className="c-prompt">$ </span>
                  <span className="c-cmd">
                    python ingest.py --pdf handbook.pdf --recreate
                  </span>
                  <span className="c-dim"> # optional CLI fallback</span>
                </div>
                <div className="c-ok"> ✔ Indexed handbook.pdf — 132 pages, 486 chunks</div>
                <div>
                  <span className="c-dim"># open http://localhost:5173 and ask away</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Closing CTA */}
      <section className="container">
        <div className="cta">
          <span className="eyebrow">Get Started</span>
          <h2>Stop rebuilding RAG from scratch. Start with RAG Starter.</h2>
          <div className="cta__ctas">
            <LinkButton size="lg" to="/signup">
              Get Started
              <ArrowRight size={16} />
            </LinkButton>
            <LinkButton variant="secondary" size="lg" to="/docs">
              View Documentation
            </LinkButton>
          </div>
        </div>
      </section>

      <MarketingFooter />
    </div>
  )
}
